FROM bitnami/spark:3.5.1

USER root
# Installer pandas et pyarrow
RUN pip install pandas pyarrow

# (optionnel) si tu veux copier ton code
COPY requirements.txt .
RUN pip install -r requirements.txt
USER 1001 